from __future__ import annotations

from typing import Iterable, Protocol

from duckkb.domain.models import Chunk


class SearchIndexRepo(Protocol):
    def clear_index(self) -> None: ...

    def insert_chunks(self, chunks: Iterable[Chunk]) -> int: ...

    def search_by_tokens(self, tokens: list[str], limit: int) -> list[Chunk]: ...


class CacheRepo(Protocol):
    def get_embedding(self, content_hash: str) -> list[float] | None: ...

    def put_embedding(self, content_hash: str, vector: list[float]) -> None: ...

    def touch(self, content_hash: str) -> None: ...

    def gc(self, max_days: int) -> int: ...


class SchemaRepo(Protocol):
    def load_schema_sql(self) -> str: ...

    def ensure_schema(self) -> None: ...

    def get_er_mermaid(self) -> str: ...


class ImportRepo(Protocol):
    def list_data_files(self) -> list[str]: ...

    def read_jsonl_lines(self, file_path: str) -> list[str]: ...

    def write_table_jsonl(self, table_name: str, lines: list[str]) -> None: ...
